dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- otree test public_goods
- otree test guess_two_thirds
env:
  global:
  - secure: pvi+UAUk8UJ3DKL2TZKBvtI3s1eKEJzvjl3Cm6NJ4aVhIa7XLbu03BGTbXiCSjDBaZqaMlY5o9+sgOk73wPHgOSHbqANucvuKOQHrU0+vbAYXQWAJtVsYQ+4kKRWMK6bzbAIUCBLLIVT4ib8Lz6l9Dtup8+QAv9F5yjK6YrLSnMaIUkgY5KthY4jC1nu5UAxzbmQyHqzL28dJe6BLoRm9EOJg1/4xfTOotL+EKJ9ncuZmLUiPD+iRb05KfPAS1YeG6v2NrQA7zyNLbdf1JL+v2xMoqh1HgLwCwMLNJLptMRsW67iZc1ICDt+FSW4vn7W2WEFMTZ87VfO0xMJ/w3cSYOYD1EJVmzPOrs17MJOZFNxxRqpSYTL8PDt+fGsjWm2VlXxNJdiX+j5zBlmDC2/Ok/KtGUPcT7R+Dy09ZpJJysc3IbEL72Uqocvxz6woYVeLMKZLFU/d9RYWovLQv+o4kbflGrQIn9j1td0i5FcPM7cbTOcJfWnuBzD8dFsySAc/is4kT5ceAwFzp+AE9XgNqcEzf4KtRuV3xmTHpLexxa9qlftgMhtlfEacLQVGXkVTCGLGJtHCI3VGWxlasmfX8jbkhUQWnt8LbPz0hwlUNqkpuvgsIlrAQqzjndTaEhjKbJlsngpp8UyIxeZDPb1cYQOHscli/4gInV18S73wQU=
